FROM ubuntu:20.04

USER root
WORKDIR /openspa

RUN mkdir /openspa/clients
RUN apt update \
    && apt install iputils-ping  -y --no-install-recommends --no-install-suggests

COPY docker-entrypoint-client.sh docker-entrypoint.sh
COPY openspa-client .
COPY openspa-tools .

ENTRYPOINT ["./docker-entrypoint.sh"]

EXPOSE 22211

